---
title: "C5_A1"
output: html_document
date: "2025-02-19"
---

```{r}
library(dplyr)
```


```{r Setup}
fileUrl <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
destFile <- "activity.zip"
download.file(fileUrl,destFile )
unzip(destFile)
df <- read.csv("activity.csv")
```

```{r What is mean total number of steps taken per day?}
#Calculate the total number of steps taken per day
totalStepsPerDay <- summarize(group_by(df, date), totalSteps = sum(steps, na.rm = TRUE))
print(totalStepsPerDay)
#Calculate and report the mean and median of the total number of steps taken per day
print(paste("Total number of steps per day ::::  MEAN", as.character(mean(totalStepsPerDay$totalSteps)), "median", as.character(median(totalStepsPerDay$totalSteps))))
#If you do not understand the difference between a histogram and a barplot, research the difference between them. Make a histogram of the total number of steps taken each day

```
```{r}
hist(totalStepsPerDay$totalSteps, xlab = "number of steps taken", main = "Hist of total steps per day")
barplot(totalStepsPerDay$totalSteps, name = unique(df$date), xlab = "number of steps taken", main = "Barplot of total Steps per day")
```

### What is the average daily activity pattern?

```{r What is the average daily activity pattern?}
#Make a time series plot (i.e.type = "l") of the 5-minute interval (x-axis) and the average number of #steps taken, averaged across all days (y-axis)
grouppedByInterval = with(df,tapply(steps, interval, mean, na.rm=TRUE))

#Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
print(paste("The interval that contain, on average, the maximum number of steps is : ", as.character(unique(df$interval)[which.max(grouppedByInterval)]), " minutes"))

```

```{r}
plot(unique(df$interval, grouppedByInterval), type = "l", col="blue", main="Steps vs Interval", xlab = "5min interval", ylab = "steps")
```


```{r}

imputeNA <- function (mydf)
{
  meanDF = summarize(group_by(imputedDF, interval), meanSteps = median(steps, na.rm = TRUE))
  for(inter in unique(meanDF$interval))
  {
    mydf[(mydf$interval == inter) & is.na(mydf$steps),]$steps <- meanDF[meanDF$interval == inter, ]$meanSteps
  }
  return (mydf)
}
# 1.- Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs
imputedDF <- df
print(paste("The total number of NAs is ", sum(is.na(imputedDF$steps))))

imputedDF<- imputeNA( imputedDF)

totalStepsPerDayImputed = summarize(group_by(imputedDF,date), totalSteps = sum(steps, na.rm = TRUE))

print(paste("Total number of steps per day ::::  MEAN", as.character(mean(totalStepsPerDayImputed$totalSteps)), "median", as.character(median(totalStepsPerDayImputed$totalSteps))))


```
```{r}
hist(totalStepsPerDayImputed$totalSteps, xlab = "number of steps taken", main = "Hist of total steps per day")
barplot(totalStepsPerDayImputed$totalSteps, name = unique(imputedDF$date), xlab = "number of steps taken", main = "Barplot of total Steps per day(imputed)")
```


```{r}
imputedDF <- mutate(imputedDF, date = weekdays(strptime(date , format = "%Y-%m-%d")))
imputedDF <- mutate(imputedDF, weekday = date %in% c("Sunday", "Saturday"), weektype = 'temp')
imputedDF[imputedDF$weekday,]$weektype <- "weekend"
imputedDF[!imputedDF$weekday,]$weektype <- "weekday"

par(mfrow=c(2,1))
weekEndDays<-imputedDF[imputedDF$weekday, ]
weekNormalDays<-imputedDF[!imputedDF$weekday, ]

grouppedWeekEnd <- with(weekEndDays, tapply(steps,interval, mean, rm.na = TRUE))
grouppedNormal <- with(weekNormalDays,tapply(steps,interval, mean, rm.na = TRUE) )
plot(unique(imputedDF$interval), grouppedWeekEnd, type = "l", col = "green", xlab = "interval", ylab = "# steps", main = "WeekEnd")
plot(unique(imputedDF$interval), grouppedNormal, type = "l",col = "green", xlab = "interval", ylab = "# steps", main = "Weekday")
```

